// <auto-generated />
using CSProjeDemo1.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSProjeDemo1.Data.Migrations
{
    [DbContext(typeof(KutuphaneContext))]
    partial class KutuphaneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KitapDurumu")
                        .HasColumnType("int");

                    b.Property<string>("KitapTuru")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int");

                    b.Property<int>("YayinYili")
                        .HasColumnType("int");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UyeId");

                    b.ToTable("Kitaplar");

                    b.HasDiscriminator<string>("KitapTuru").HasValue("Kitap");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.Uye", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UyeNumarasi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.KitapBilim", b =>
                {
                    b.HasBaseType("CSProjeDemo1.Core.Entities.Kitap");

                    b.HasDiscriminator().HasValue("Bilim");
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.KitapRoman", b =>
                {
                    b.HasBaseType("CSProjeDemo1.Core.Entities.Kitap");

                    b.HasDiscriminator().HasValue("Roman");
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.KitapTarih", b =>
                {
                    b.HasBaseType("CSProjeDemo1.Core.Entities.Kitap");

                    b.HasDiscriminator().HasValue("Tarih");
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.Kitap", b =>
                {
                    b.HasOne("CSProjeDemo1.Core.Entities.Uye", null)
                        .WithMany("OduncAldigiKitaplar")
                        .HasForeignKey("UyeId");
                });

            modelBuilder.Entity("CSProjeDemo1.Core.Entities.Uye", b =>
                {
                    b.Navigation("OduncAldigiKitaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
